name: Deploy

on:
    release:
        types:
            - released

jobs:
    publish-marketplace:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 16.x

            - name: Install
              run: yarn install --frozen-lockfile

            - name: Deploy to marketplace
              run: yarn deploy
              env:
                  VSCE_PAT: ${{ secrets.VSCE_PAT }}
